# Generated by Django 3.2.9 on 2021-11-21 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_account', models.CharField(max_length=15, verbose_name='Лицевой счет')),
                ('mounth', models.CharField(choices=[('January', 'Январь'), ('February', 'Февраль'), ('March', 'Март'), ('April', 'Апрель'), ('May', 'Май'), ('June', 'Июнь'), ('July', 'Июль'), ('August', 'Август'), ('September', 'Сентябрь'), ('October', 'Октябрь'), ('November', 'Ноябрь'), ('December', 'Декабрь')], max_length=10, verbose_name='Месяц')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('payment_amount', models.FloatField(verbose_name='Сумма платежа')),
                ('indications', models.TextField(null=True, verbose_name='Показания счетчиков')),
                ('electronic_receipt_filename', models.TextField(null=True, verbose_name='Название файла с электронной квитанцией')),
                ('address', models.TextField(null=True, verbose_name='Адрес квартиры')),
                ('paid_for', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('service_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.service', verbose_name='Тип платежа')),
            ],
        ),
    ]
