# Generated by Django 3.2.9 on 2021-11-21 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_bill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bill',
            new_name='Account',
        ),
    ]
