# Generated by Django 3.2.9 on 2021-11-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_rename_bill_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='paid_for',
        ),
        migrations.AddField(
            model_name='account',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
    ]
